using System;
using System.Collections.Generic;
using System.Linq;
using UrbanWildlife.City;
using UrbanWildlife.Construction;

namespace UrbanWildlife.Prototype
{
    public static class CityPrototypeStateFactory
    {
        public static CityState Create()
        {
            CityBounds bounds = new CityBounds
            {
                origin = "top_left",
                width_units = 90f,
                height_units = 60f,
            };
            CityBuilding[] buildings =
            {
                // The opening state is deliberately sparse. The denser reference is the
                // player's destination, not pre-authored scenery.
                Building("detached-garden", CityBuildingType.DetachedHouse, 110, 0.277778f, 0.25f, 12, 0.35f, 0.15f, 4, 0.45f),
                Building("detached-east", CityBuildingType.DetachedHouse, 111, 0.50f, 0.25f, 12, 0.35f, 0.15f, 4, 0.45f),
            };
            CityPlanningGrid planningGrid = CreatePlanningGrid(buildings, bounds);

            float[][] mainRoadPoints = SmoothPoints(
                (0.00f, 0.285f),
                (0.08f, 0.290f),
                (0.16f, 0.340f),
                (0.25f, 0.370f),
                (0.34f, 0.425f),
                (0.43f, 0.425f),
                (0.53f, 0.390f),
                (0.60f, 0.395f),
                (0.66f, 0.440f),
                (0.70f, 0.490f),
                (0.78f, 0.520f),
                (0.86f, 0.510f),
                (1.00f, 0.460f));

            CityVehicleRoad[] mainRoads =
            {
                new CityVehicleRoad
                {
                    id = "vehicle-main-street",
                    role = CityVehicleRoadRole.Main,
                    route_option = CityRoadRouteOption.Existing,
                    construction_state = CityConstructionState.Existing,
                    source = CityNetworkSource.ExistingMap,
                    points_norm = mainRoadPoints,
                    width_units = 1.1f,
                    speed_units_per_second = 7f,
                    traffic_load = 0.46f,
                    connected_building_ids = buildings.Select(building => building.id).ToArray(),
                    connected_road_ids = Array.Empty<string>(),
                },
            };

            CityPedestrianLink[] mainLinks =
            {
                new CityPedestrianLink
                {
                    id = "pedestrian-park-spine",
                    type = CityPedestrianLinkType.ExistingNetwork,
                    construction_state = CityConstructionState.Existing,
                    source = CityNetworkSource.ExistingMap,
                    points_norm = OffsetY(mainRoadPoints, -0.018f),
                    width_units = 0.75f,
                    step_free_accessible = true,
                    connected_building_ids = buildings.Select(building => building.id).ToArray(),
                    connected_link_ids = Array.Empty<string>(),
                },
            };

            List<CityVehicleRoad> roads = new List<CityVehicleRoad>(mainRoads);
            List<CityPedestrianLink> links = new List<CityPedestrianLink>(mainLinks);
            foreach (CityBuilding building in buildings)
            {
                string roadNetwork = "vehicle-main-street";
                string linkNetwork = "pedestrian-park-spine";
                string roadId = $"road-access-{building.id}";
                string linkId = $"walk-access-{building.id}";
                float roadY = InterpolateYAtX(mainRoadPoints, building.position_norm[0]);
                float linkY = roadY - 0.018f;
                float buildingEdgeY = building.position_norm[1] +
                                      building.footprint_units[1] / bounds.height_units * 0.46f;
                roads.Add(new CityVehicleRoad
                {
                    id = roadId,
                    role = CityVehicleRoadRole.BuildingAccess,
                    route_option = CityRoadRouteOption.ExistingNetwork,
                    construction_state = CityConstructionState.Existing,
                    source = CityNetworkSource.AutoGenerated,
                    points_norm = Points(
                        (building.position_norm[0], buildingEdgeY),
                        (building.position_norm[0], (buildingEdgeY + roadY) * 0.5f),
                        (building.position_norm[0], roadY)),
                    width_units = 0.45f,
                    speed_units_per_second = 4.5f,
                    traffic_load = building.vehicle_demand * 0.5f,
                    connected_building_ids = new[] { building.id },
                    connected_road_ids = new[] { roadNetwork },
                });
                links.Add(new CityPedestrianLink
                {
                    id = linkId,
                    type = CityPedestrianLinkType.BasicBuildingAccess,
                    construction_state = CityConstructionState.Existing,
                    source = CityNetworkSource.AutoGenerated,
                    points_norm = Points(
                        (building.position_norm[0] + 0.008f, buildingEdgeY),
                        (building.position_norm[0], linkY)),
                    width_units = 0.16f,
                    step_free_accessible = true,
                    connected_building_ids = new[] { building.id },
                    connected_link_ids = new[] { linkNetwork },
                });
                building.vehicle_road_ids = new[] { roadId };
                building.pedestrian_link_ids = new[] { linkId };
            }

            CityGreenPatch[] patches = CreateGreenPatches(planningGrid, bounds);

            CityAmenity[] amenities = Array.Empty<CityAmenity>();

            CityWasteNode[] wasteNodes = buildings.Select(building => new CityWasteNode
            {
                id = $"waste-{building.id}",
                type = CityWasteNodeType.BuildingOutput,
                source_building_id = building.id,
                position_norm = (float[])building.position_norm.Clone(),
                generation_rate = building.waste_output,
                capacity = 0f,
                fill_ratio = 0f,
            }).ToArray();

            CityState city = new CityState
            {
                city_id = "city-prototype-v01",
                revision = 5,
                source_contract = "city-prototype-demo-0.1",
                bounds = bounds,
                planning_grid = planningGrid,
                buildings = buildings,
                green_patches = patches,
                vehicle_roads = roads.ToArray(),
                pedestrian_links = links.ToArray(),
                amenities = amenities,
                waste = new CityWasteSystem
                {
                    total_demand = buildings.Sum(building => building.waste_output),
                    total_capacity = 0f,
                    overflow_elapsed_seconds = 0f,
                    overflow_active = false,
                    nodes = wasteNodes,
                    litter_hotspots = Array.Empty<CityLitterHotspot>(),
                },
            };
            CityStateValidationResult validation = CityStateValidator.Validate(city);
            if (!validation.IsValid)
            {
                throw new InvalidOperationException($"Prototype city is invalid: {validation.Summary}");
            }
            return city;
        }

        private static CityBuilding Building(
            string id,
            CityBuildingType type,
            int tokenId,
            float x,
            float y,
            int housing,
            float origin,
            float destination,
            int capacity,
            float vehicleDemand)
        {
            bool commercial = type == CityBuildingType.Commercial;
            bool community = type == CityBuildingType.CommunityFacility;
            return new CityBuilding
            {
                id = id,
                source_token_id = tokenId,
                type = type,
                construction_state = CityConstructionState.Existing,
                position_norm = new[] { x, y },
                rotation_deg = 0f,
                footprint_units = CityConstructionFactory.ReferenceFootprintUnits(type),
                housing_capacity = housing,
                human_origin_rate = origin,
                human_destination_weight = destination,
                comfortable_capacity = capacity,
                vehicle_demand = vehicleDemand,
                waste_output = commercial ? 0.9f : community ? 0.55f : housing > 20 ? 0.75f : 0.3f,
                anthropogenic_food_output = commercial ? 0.85f : community ? 0.3f : 0.2f,
                disturbance_output = commercial ? 0.85f : community ? 0.65f : housing > 20 ? 0.8f : 0.35f,
                requires_vehicle_access = true,
                requires_pedestrian_access = true,
            };
        }

        private static CityPlanningGrid CreatePlanningGrid(
            IEnumerable<CityBuilding> buildings,
            CityBounds bounds)
        {
            CityPlanningGrid grid = new CityPlanningGrid
            {
                cols = CityPlanningGrid.DefaultColumns,
                rows = CityPlanningGrid.DefaultRows,
                max_active_player_buildings = 9,
                cells = Enumerable.Range(0, CityPlanningGrid.DefaultRows)
                    .SelectMany(row => Enumerable.Range(0, CityPlanningGrid.DefaultColumns)
                        .Select(col => CreateGridCell(row, col)))
                    .ToArray(),
            };

            foreach (CityBuilding building in buildings ?? Array.Empty<CityBuilding>())
            {
                if (!CityGridResolver.TryOccupyWithBuilding(
                        grid,
                        bounds,
                        building,
                        0,
                        out string error))
                {
                    throw new InvalidOperationException(
                        $"Could not place baseline building {building.id} on the planning grid: {error}");
                }
            }
            return grid;
        }

        private static CityGridCell CreateGridCell(int row, int col)
        {
            CityLandCover cover = BaselineCover(row, col);
            bool fixedFeature = cover == CityLandCover.PublicGreen ||
                                cover == CityLandCover.Water ||
                                cover == CityLandCover.CivicPlaza;
            string habitatId = cover == CityLandCover.Woodland ||
                               cover == CityLandCover.PublicGreen
                ? HabitatPatchId(row, col, cover)
                : null;
            return new CityGridCell
            {
                id = CellId(row, col),
                row = row,
                col = col,
                center_norm = new[]
                {
                    (col + 0.5f) / CityPlanningGrid.DefaultColumns,
                    (row + 0.5f) / CityPlanningGrid.DefaultRows,
                },
                size_norm = new[]
                {
                    1f / CityPlanningGrid.DefaultColumns,
                    1f / CityPlanningGrid.DefaultRows,
                },
                baseline_cover = cover,
                current_cover = cover,
                buildable = !fixedFeature,
                fixed_feature = fixedFeature,
                occupant_id = null,
                habitat_patch_id = habitatId,
                was_woodland = cover == CityLandCover.Woodland,
                last_changed_revision = 0,
            };
        }

        private static CityLandCover BaselineCover(int row, int col)
        {
            // Preserve the approved organic woodland/open-land zoning while subdividing each
            // former 10 x 10 planning area into four 5 x 5 ecological/occupancy cells.
            int zoneRow = row / 2;
            int zoneCol = col / 2;
            bool woodland = zoneRow == 0 || zoneRow == 5 ||
                            (zoneRow == 1 && (zoneCol <= 2 || zoneCol == 4 || zoneCol >= 6)) ||
                            (zoneRow == 2 && (zoneCol <= 1 || zoneCol == 4 || zoneCol >= 7)) ||
                            (zoneRow == 3 && (zoneCol <= 1 || zoneCol >= 7)) ||
                            (zoneRow == 4 && (zoneCol <= 3 || zoneCol >= 7));
            if (woodland)
            {
                return CityLandCover.Woodland;
            }
            return CityLandCover.OpenLand;
        }

        private static CityGreenPatch[] CreateGreenPatches(
            CityPlanningGrid grid,
            CityBounds bounds)
        {
            CityGridCell[] habitatCells = grid.cells
                .Where(cell => cell != null &&
                               !string.IsNullOrWhiteSpace(cell.habitat_patch_id))
                .OrderBy(cell => cell.row)
                .ThenBy(cell => cell.col)
                .ToArray();
            HashSet<string> habitatCellIds = new HashSet<string>(
                habitatCells.Select(cell => cell.id));
            return habitatCells.Select(cell =>
            {
                bool woodland = cell.current_cover == CityLandCover.Woodland;
                string[] connected = CityGridResolver.GetFourNeighbours(grid, cell.id)
                    .Where(neighbour => habitatCellIds.Contains(neighbour.id))
                    .Select(neighbour => neighbour.habitat_patch_id)
                    .Where(id => !string.IsNullOrWhiteSpace(id))
                    .ToArray();
                return new CityGreenPatch
                {
                    id = cell.habitat_patch_id,
                    source_token_id = -1,
                    planning_cell_id = cell.id,
                    type = woodland ? CityGreenPatchType.Woodland : CityGreenPatchType.OpenGrass,
                    construction_state = CityConstructionState.Existing,
                    public_park = !woodland,
                    polygon_norm = CityGridResolver.PolygonFor(cell),
                    shelter_value = woodland ? 0.88f : 0.30f,
                    natural_food_value = woodland ? 0.80f : 0.28f,
                    human_disturbance = woodland ? 0.12f : 0.46f,
                    patch_size_units = cell.size_norm[0] * bounds.width_units *
                                       cell.size_norm[1] * bounds.height_units,
                    connected_patch_ids = connected,
                };
            }).ToArray();
        }

        private static string HabitatPatchId(int row, int col, CityLandCover cover)
        {
            string prefix = cover == CityLandCover.Woodland ? "woodland" : "public-green";
            return $"{prefix}-cell-{CellId(row, col).ToLowerInvariant()}";
        }

        private static string CellId(int row, int col)
        {
            return $"{(char)('A' + row)}{col + 1}";
        }

        private static CityAmenity Amenity(
            string id,
            CityAmenityType type,
            float x,
            float y,
            float radius,
            float activity,
            float capacity,
            float exposureReduction)
        {
            return new CityAmenity
            {
                id = id,
                type = type,
                construction_state = CityConstructionState.Existing,
                position_norm = new[] { x, y },
                service_radius_units = radius,
                human_activity_weight = activity,
                waste_capacity = capacity,
                food_exposure_reduction = exposureReduction,
            };
        }

        private static float[][] Points(params (float x, float y)[] points)
        {
            return points.Select(point => new[] { point.x, point.y }).ToArray();
        }

        private static float[][] SmoothPoints(params (float x, float y)[] controlPoints)
        {
            const int SamplesPerSegment = 4;
            List<float[]> points = new List<float[]>();
            for (int index = 0; index < controlPoints.Length - 1; index += 1)
            {
                (float x, float y) p0 = controlPoints[Math.Max(0, index - 1)];
                (float x, float y) p1 = controlPoints[index];
                (float x, float y) p2 = controlPoints[index + 1];
                (float x, float y) p3 = controlPoints[Math.Min(controlPoints.Length - 1, index + 2)];
                for (int sample = 0; sample < SamplesPerSegment; sample += 1)
                {
                    float t = sample / (float)SamplesPerSegment;
                    float t2 = t * t;
                    float t3 = t2 * t;
                    points.Add(new[]
                    {
                        0.5f * ((2f * p1.x) + (-p0.x + p2.x) * t +
                                (2f * p0.x - 5f * p1.x + 4f * p2.x - p3.x) * t2 +
                                (-p0.x + 3f * p1.x - 3f * p2.x + p3.x) * t3),
                        0.5f * ((2f * p1.y) + (-p0.y + p2.y) * t +
                                (2f * p0.y - 5f * p1.y + 4f * p2.y - p3.y) * t2 +
                                (-p0.y + 3f * p1.y - 3f * p2.y + p3.y) * t3),
                    });
                }
            }
            (float x, float y) last = controlPoints[controlPoints.Length - 1];
            points.Add(new[] { last.x, last.y });
            return points.ToArray();
        }

        private static float[][] OffsetY(float[][] points, float offset)
        {
            return points.Select(point => new[] { point[0], point[1] + offset }).ToArray();
        }

        private static float InterpolateYAtX(float[][] points, float x)
        {
            for (int index = 0; index < points.Length - 1; index += 1)
            {
                float[] start = points[index];
                float[] end = points[index + 1];
                if (x < start[0] || x > end[0])
                {
                    continue;
                }
                float span = Math.Max(0.0001f, end[0] - start[0]);
                float t = (x - start[0]) / span;
                return start[1] + (end[1] - start[1]) * t;
            }
            return points[points.Length - 1][1];
        }
    }
}
