using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace UrbanWildlife.City
{
    public static class CityStateContract
    {
        public const string SchemaVersion = "0.1";
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CityBuildingType
    {
        Apartment,
        DetachedHouse,
        Commercial,
        CommunityFacility,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CityGreenPatchType
    {
        Woodland,
        ShrubGarden,
        OpenGrass,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CityConstructionState
    {
        Existing,
        Proposed,
        UnderConstruction,
        DemolitionProposed,
        Demolishing,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CityVehicleRoadRole
    {
        Main,
        Local,
        BuildingAccess,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CityRoadRouteOption
    {
        Existing,
        Direct,
        ExistingNetwork,
        LowImpact,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CityPedestrianLinkType
    {
        ExistingNetwork,
        BasicBuildingAccess,
        ExtraFootpath,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CityNetworkSource
    {
        ExistingMap,
        AutoGenerated,
        ScreenEdited,
        LegacyAdapter,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CityWasteNodeType
    {
        BuildingOutput,
        Bin,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CityAmenityType
    {
        Bench,
        Bin,
    }

    [Serializable]
    public sealed class CityState
    {
        public string schema_version = CityStateContract.SchemaVersion;
        public string city_id;
        public int revision;
        public string source_contract;
        public CityBounds bounds;
        public CityPlanningGrid planning_grid;
        public CityBuilding[] buildings = Array.Empty<CityBuilding>();
        public CityGreenPatch[] green_patches = Array.Empty<CityGreenPatch>();
        public CityVehicleRoad[] vehicle_roads = Array.Empty<CityVehicleRoad>();
        public CityPedestrianLink[] pedestrian_links = Array.Empty<CityPedestrianLink>();
        public CityAmenity[] amenities = Array.Empty<CityAmenity>();
        public CityWasteSystem waste = new CityWasteSystem();
    }

    [Serializable]
    public sealed class CityBounds
    {
        public string origin = "top_left";
        public float width_units;
        public float height_units;
    }

    [Serializable]
    public sealed class CityBuilding
    {
        public string id;
        public int source_token_id = -1;
        public string planning_cell_id;
        public CityBuildingType type;
        public CityConstructionState construction_state;
        public float[] position_norm;
        public float rotation_deg;
        public float[] footprint_units;
        public int housing_capacity;
        public float human_origin_rate;
        public float human_destination_weight;
        public int comfortable_capacity;
        public float vehicle_demand;
        public float waste_output;
        public float anthropogenic_food_output;
        public float disturbance_output;
        public bool requires_vehicle_access;
        public bool requires_pedestrian_access = true;
        public string[] vehicle_road_ids = Array.Empty<string>();
        public string[] pedestrian_link_ids = Array.Empty<string>();
    }

    [Serializable]
    public sealed class CityGreenPatch
    {
        public string id;
        public int source_token_id = -1;
        public string planning_cell_id;
        public CityGreenPatchType type;
        public CityConstructionState construction_state;
        public bool public_park;
        public float[][] polygon_norm;
        public float shelter_value;
        public float natural_food_value;
        public float human_disturbance;
        public float patch_size_units;
        public string[] connected_patch_ids = Array.Empty<string>();
    }

    [Serializable]
    public sealed class CityVehicleRoad
    {
        public string id;
        public CityVehicleRoadRole role;
        public CityRoadRouteOption route_option;
        public CityConstructionState construction_state;
        public CityNetworkSource source;
        public float[][] points_norm;
        public float width_units;
        public float speed_units_per_second;
        public float traffic_load;
        public string[] connected_building_ids = Array.Empty<string>();
        public string[] connected_road_ids = Array.Empty<string>();
    }

    [Serializable]
    public sealed class CityPedestrianLink
    {
        public string id;
        public CityPedestrianLinkType type;
        public CityConstructionState construction_state;
        public CityNetworkSource source;
        public float[][] points_norm;
        public float width_units;
        public bool step_free_accessible;
        public string[] connected_building_ids = Array.Empty<string>();
        public string[] connected_link_ids = Array.Empty<string>();
    }

    [Serializable]
    public sealed class CityWasteSystem
    {
        public float total_demand;
        public float total_capacity;
        public float overflow_elapsed_seconds;
        public bool overflow_active;
        public CityWasteNode[] nodes = Array.Empty<CityWasteNode>();
        public CityLitterHotspot[] litter_hotspots = Array.Empty<CityLitterHotspot>();
    }

    [Serializable]
    public sealed class CityAmenity
    {
        public string id;
        public CityAmenityType type;
        public CityConstructionState construction_state;
        public float[] position_norm;
        public float service_radius_units;
        public float human_activity_weight;
        public float waste_capacity;
        public float food_exposure_reduction;
    }

    [Serializable]
    public sealed class CityWasteNode
    {
        public string id;
        public CityWasteNodeType type;
        public string source_building_id;
        public float[] position_norm;
        public float generation_rate;
        public float capacity;
        public float fill_ratio;
    }

    [Serializable]
    public sealed class CityLitterHotspot
    {
        public string id;
        public string source_id;
        public float[] position_norm;
        public float intensity;
    }
}
